# setinngan deploy

spring.application.name=backend

spring.datasource.url=jdbc:mysql://148.230.96.168:3306/db_cancer
spring.datasource.username=mat
spring.datasource.password=mat123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080

#url.predict = http://localhost:8000/models
url.predict = http://srv1067742.hstgr.cloud/models
app.cors.allowed-origins = http://srv1067742.hstgr.cloud
app.upload.dir=uploads/

# settingan local
#spring.application.name=backend
#
#spring.datasource.url=jdbc:mysql://localhost:3306/db_cancer
#spring.datasource.username=root
#spring.datasource.password=
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#
#server.port=8080
#
#url.predict = http://localhost:8000/models
##url.predict = http://srv1067742.hstgr.cloud/models
#app.cors.allowed-origins = http://localhost:4200
#app.upload.dir=uploads/